# Пример конфигурации тестового Control-сервера (example-server)

listen_addr: "127.0.0.1:8080"   # адрес и порт прослушивания

# Учётные данные тестового пользователя
user_login: "test"
user_password: "test"

# Папка с описаниями серверов и Core-конфигурациями
profiles_dir: "./profiles"

